create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "content" text not null,
    "mail" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."messages" enable row level security;

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";



